### ISSUE TITLE
4th History Credit Not Being Marked Correctly

### ISSUE THREAD

**Issue by 1587479** [greenturtle1134/tj-planner#46]
Problem: 4th History Credit Not Being Marked Correctly
![Capture](https://user-images.githubusercontent.com/68449565/89035817-8b181880-d309-11ea-9c45-a83422f70c0d.PNG)

**Comment by greenturtle1134** [comment]
It's not just the fourth history credit, I managed to break pretty much all of the requirements with the last update.

Fixing.
